version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./public:/crud_php/public
        depends_on:
            - mysql
        restart: always
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./public:/crud_php/public
        restart: always
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'KriShna824@32'
            MYSQL_USER: 'krishna'
            MYSQL_PASSWORD: 'KriShna824@32'
            MYSQL_DATABASE: 'test'
        volumes:
            - site1:/var/lib/mysql
        ports:
            - 3307:3306
        restart: always
volumes:
    site1: {}